### ISSUE TITLE
No menu option after docker pull. 

### ISSUE THREAD

**Issue by Kein90** [electerm/electerm-web-docker#2]
Hi! I ran the script to get Electerm web using docker and after it installed all it loads is the software logo and no other options. 

![image](https://github.com/electerm/electerm-web-docker/assets/151675537/6da1b596-1dbe-4478-af31-7366b4c711ba)

This is the code I ran (minus the sensitive part). I tried to load it in private mode, in a different browser, without any addons but no change. 
```
sudo docker run --init -v /backup/electerm:/home/electerm/data \
  -e "DB_PATH=/home/electerm/data" \
  -e "HOST=0.0.0.0" \
  -e "SERVER=http://0.0.0.0:8082" \
  -e "SERVER_SECRET=******"\
  -e "SERVER_PASS=*******" \
  -e "ENABLE_AUTH=1" \
  -p 8082:8082\
  zxdong262/electerm-web
```
----------------------------------

This is the log I get: 

#21:26:09 info › app start
21:26:09 info › server runs on http://0.0.0.0:5577
GET / 304 - - 162.724 ms
GET /images/electerm.png 304 - - 3.206 ms
GET /images/electerm-watermark.png 304 - - 1.807 ms
GET /favicon.ico 304 - - 1.267 ms
GET / 304 - - 2.180 ms
GET /images/electerm.png 304 - - 0.946 ms
GET /images/electerm-watermark.png 304 - - 0.896 ms
GET /favicon.ico 304 - - 0.978 ms
GET / 304 - - 3.186 ms
GET /images/electerm.png 304 - - 1.697 ms
GET /images/electerm-watermark.png 304 - - 0.928 ms
GET /favicon.ico 304 - - 1.175 ms
GET / 304 - - 2.640 ms
GET /images/electerm.png 304 - - 1.356 ms
GET /images/electerm-watermark.png 304 - - 0.929 ms
GET /favicon.ico 304 - - 0.821 ms#

------------------------------------------

Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:58 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:58 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

-------------------------------------------------

Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

**Comment by zxdong262** [comment]
Can you check browser developer tool console/network, any error there?

**Comment by zxdong262** [comment]
If you want directly visit using ip, should bind like:

```bash
sudo docker run --init -v /backup/electerm:/home/electerm/data \
  -e "DB_PATH=/home/electerm/data" \
  -e "HOST=0.0.0.0" \
  -e "SERVER=http://your-ip:8082" \
  -e "SERVER_SECRET=******"\
  -e "SERVER_PASS=*******" \
  -e "ENABLE_AUTH=1" \
  -p 8082:8082\
  zxdong262/electerm-web
```

then visit http://your-ip:8082, 

bind SERVER=http://0.0.0.0:8082, visit from http://your-ip:8082 from internet would not work.

**Comment by Kein90** [comment]
Had the following browser console errors: 

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
0.0.0.0:8082/css/2.37.96-index.css:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
1**.***.***.***/:18 Unchecked runtime.lastError: The message port closed before a response was received.
0.0.0.0:8082/js/basic-2.37.96.js:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT 


The whole thing was fixed with your suggestion '`-e "SERVER=http://your-ip:8082" \`'. 
Thank you!
