### ISSUE TITLE
Inaccessible interface in new version

### ISSUE THREAD

**Issue by furriest** [electerm/electerm-web-docker#4]
Hello!

When I tried to create a new container, I got a black screen in the browser and this log:
```
#docker run --init --name electerm -v /opt/electerm/data:/home/electerm/data -e "DB_PATH=/home/electerm/data"  -e "HOST=0.0.0.0"  -e "SERVER=http://192.168.0.14:8082"  -p 8082:5577 zxdong262/electerm-web

09:43:34 info › app start
09:43:34 info › server runs on http://0.0.0.0:5577
GET / 200 22004 - 100.268 ms
GET /css/2.38.11-basic.css 404 160 - 13.748 ms
GET /css/2.38.11-index.css 404 160 - 11.990 ms
GET /js/basic-2.38.11.js 404 158 - 10.776 ms
GET /images/electerm.png 404 158 - 10.207 ms
GET /images/electerm-watermark.png 404 168 - 1.447 ms

```

So it looks like the web server inside the container lost its path to the files.

After I switched back to the 2.37.128 — the service started successfully. 

Are there some changes in new versions which can provide such an effect? 
Do I need to change a start command somehow?

**Comment by zxdong262** [comment]
Thank you for the feedback, fixed now. Latest(2.38.12) should work now.

**Comment by furriest** [comment]
Thank you, it works!
