### ISSUE TITLE
求一个搭建教程。。。官方的看不明白 Looking for a building tutorial. . . I can’t understand the official one

### ISSUE THREAD

**Issue by 125540947** [electerm/electerm-web-docker#5]
求一个搭建教程。。。官方的看不懂 Looking for a building tutorial. . . I can’t understand the official one

**Comment by zxdong262** [comment]
加了一个中文的 https://github.com/electerm/electerm-web-docker/blob/main/README_cn.md 可以试试

**Comment by wangweitung** [comment]
可否增加一个端口参数，以便修改端口
- SERVER_PORT=80

**Comment by zxdong262** [comment]
> 可否增加一个端口参数，以便修改端口
> 
> * SERVER_PORT=80

把readme运行命令里的8082改成其他端口即可
